### ISSUE TITLE
ta com o foco errado, nao era hora de fazer dockerfile, cade o express rest posts? 

### ISSUE THREAD

**Issue by gabrielmancini** [bc-fullstack-01/Nathally_Backend#1]

**Comment by Nathallyleao** [comment]
Subi sem querer tudo isso, estava apanhando do Docker e fazendo uns testes e acabei subindo. Quero apagar essa branch ou apenas os arquivos para ficar apenas os commits corretos, mas estou ainda pesquisando esse comando, o senhor saberia qual seria?

Muito obrigada pelo retorno!

**Comment by gabrielmancini** [comment]
git checkout -b newbranch
git checkout master
apaga os arquivos
git add .
git commit -am 'comment'
git push origin
a new branch vai ta no seu repo tb, assim vc nao perde

**Comment by gabrielmancini** [comment]
senhor nao!
